apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../overlay-staging/aimhighergg-com
  - ../overlay-staging/alertmanager
  - ../overlay-staging/argocd
  - ../overlay-staging/argocd-api
  - ../overlay-staging/argoworkflows
  - ../overlay-staging/consul
  - ../overlay-staging/grafana
  - ../overlay-staging/grafana-login
  - ../overlay-staging/influxdb
  - ../overlay-staging/jupyterlab
  - ../overlay-staging/kubernetes-dashboard
  - ../overlay-staging/loki-backend
  - ../overlay-staging/loki-read
  - ../overlay-staging/loki-write
  - ../overlay-staging/loki-write-external
  - ../overlay-staging/longhorn
  - ../overlay-staging/mimir
  - ../overlay-staging/minio-loki
  - ../overlay-staging/minio-mimir
  - ../overlay-staging/prometheus
  - ../overlay-staging/redmine
  - ../overlay-staging/vault
  - ../overlay-staging/wiki-aimhighergg-com
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
