apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../overlay/alertmanager
  - ../overlay/argocd
  - ../overlay/argocd-api
  - ../overlay/argoworkflows
  - ../overlay/consul
  - ../overlay/grafana
  - ../overlay/grafana-login
  - ../overlay/influxdb
  - ../overlay/jupyterlab
  - ../overlay/kubernetes-dashboard
  - ../overlay/loki-backend
  - ../overlay/loki-read
  - ../overlay/loki-write
  - ../overlay/loki-write-external
  - ../overlay/longhorn
  #- ../overlay/mgmt
  #- ../overlay/mgmt-a
  - ../overlay/mimir
  - ../overlay/minio-loki
  - ../overlay/minio-mimir
  - ../overlay/prometheus
  - ../overlay/redmine
  - ../overlay/vault
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
