apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: www-aimhighergg-com
resources:
  - ../../../base-tls
transformers:
  - transformer-suffixprefix.yaml
patches:
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress-tls
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-tls
      spec:
        ingressClassName: nginx 
        tls:
        - hosts:
            - www.aimhighergg.com
          secretName: tls-secret
        rules:
        - host: www.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: www-aimhighergg-com-frontend-app01-001
                  port:
                    number: 80
            - pathType: Prefix
              path: /portfolio
              backend:
                service:
                  name: www-aimhighergg-com-frontend-static03-001
                  port:
                    number: 80
            - path: /xmlrpc.php
              pathType: ImplementationSpecific
              backend:
                service:
                  name: dummy
                  port:
                    number: 80
            - path: /debug.log
              pathType: ImplementationSpecific
              backend:
                service:
                  name: does-not-exist
                  port:
                    number: 80
            - path: /.git
              pathType: ImplementationSpecific
              backend:
                service:
                  name: dummy
                  port:
                    number: 80
            - path: /w/
              pathType: ImplementationSpecific
              backend:
                service:
                  name: dummy
                  port:
                    number: 80