apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-workflows
bases:
  - ../../base-tls
patchesStrategicMerge:
- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: cluster-issuer
  spec:
    acme:
      email: aim4highergg@gmail.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: cluster-issuer-secret
      solvers:
      - http01:
          ingress:
            class: nginx
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-tls
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
      nginx.ingress.kubernetes.io/use-regex: 'true'
      nginx.ingress.kubernetes.io/whitelist-source-range: '192.168.1.0/24'
  spec:
    ingressClassName: nginx
    tls:
    - hosts:
        - argoworkflows.aimhighergg.com
      secretName: tls-secret
    rules:
    - host: argoworkflows.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: argo-workflow-argo-workflows-server
              port:
                number: 2746
