apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
transformers:
  - transformer-suffixprefix.yaml
patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
      nginx.ingress.kubernetes.io/use-regex: 'true'
      nginx.ingress.kubernetes.io/whitelist-source-range: '192.168.1.0/24'
  spec:
    ingressClassName: nginx
    rules:
    - host: argocd.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /api/badge(.*)
          backend:
            service:
              name: argocd-server
              port:
                number: 80
