apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
bases:
  - ../../base
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.1/24
  spec:
    ingressClassName: nginx
    rules:
    - host: grafana.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /login(.*)
          backend:
            service:
              name: monitoring-frontend-grafana-app01-001
              port:
                number: 80