apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../../base
transformers:
  - transformer-suffixprefix.yaml
patches:
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: 'HTTP'
      spec:
        ingressClassName: nginx-service
        rules:
        - host: loki-write-external.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: monitoring-frontend-loki-write01-headless-001
                  port:
                    number: 3100
