apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base
transformers:
  - transformer-suffixprefix.yaml
patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/whitelist-source-range: 183.76.178.36/32
  spec:
    ingressClassName: nginx
    rules:
    - host: staging.grafana.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /login
          backend:
            service:
              name: monitoring-frontend-grafana-app01-001
              port:
                number: 80