apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  environment: production
  app.kubernetes.io/part-of: ingress-aggregator
fieldSpecs:
- path: metadata/labels
  create: true
