apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - ../../../base-tls
transformers:
  - transformer-suffixprefix.yaml  
patches:
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress-tls
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-tls
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.1/24
      spec:
        ingressClassName: nginx-service
        tls:
        - hosts:
            - airflow.aimhighergg.com
          secretName: tls-secret
        rules:
        - host: airflow.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: airflow-webserver
                  port:
                    number: 8080
