apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - ../../base-tls
transformers:
  - transformer-label.yaml
  - transformer-suffixprefix.yaml
patchesStrategicMerge:
- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: cluster-issuer
  spec:
    acme:
      email: aim4highergg@gmail.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        name: cluster-issuer-secret
      solvers:
      - http01:
          ingress:
            class: nginx
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-tls
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      enable-real-ip: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.1.0/24"
  spec:
    ingressClassName: nginx
    tls:
    - hosts:
        - argocd.aimhighergg.com
      secretName: tls-secret
    rules:
    - host: argocd.aimhighergg.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: argocd-server
              port:
                number: 8080
        - pathType: Prefix
          path: /login(.*)
          backend:
            service:
              name: argocd-server
              port:
                number: 8080

