apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  environment: management
  app.kubernetes.io/managed-by: github
  app.kubernetes.io/created-by: controller-manager
  app.kubernetes.io/part-of: ingress-aggregator
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/selector/matchLabels
  kind: Deployment
  create: true
- path: spec/template/metadata/labels
  kind: Deployment
  create: true