apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-vault
spec:
  acme:
    email: aim4highergg@gmail.com
    server: https://staging.vault.aimhighergg.com/v1/pki_int/acme/directory
    privateKeySecretRef:
      name: vault-pki-acme-account-key
    solvers:
    - http01:
        ingress:
          class: nginx