apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-vault
spec:
  vault:
    server: https://vault.vault.svc.cluster.local:8200
    path: pki_int/
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: argocd
        serviceAccountRef:
          name: argocd