apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-vault
  annotations:
    avp.kubernetes.io/path: "secret/data/vault/mtls"
spec:
  vault:
    server: https://staging.vault.aimhighergg.com
    path: pki_int/sign/intermidiate-role
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        serviceAccountRef:
          name: cert-manager