apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: patchesstrategicmerge
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: patchesstrategicmerge
            port:
              number: 80