apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: maintenance
resources:
  - ../../../base-tls
transformers:
  - transformer-suffixprefix.yaml
patches:
  - target:
      version: v1
      group: networking.k8s.io
      name: ingress-tls
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: ingress-tls
      spec:
        ingressClassName: nginx
        tls:
        - hosts:
            - maintenance.aimhighergg.com
          secretName: tls-secret
        rules:
        - host: maintenance.aimhighergg.com
          http:
            paths:
            - pathType: Prefix
              path: /
              backend:
                service:
                  name: maintenance 
                  port:
                    number: 80

